name: FileManager
version: ${project.version}
api-version: 1.13
main: com.github.tanokun.filemanager.FileManager
authors: [ tanoKun ]
description: Plugin for editing files. 

commands:
  files:
    description: open the files menu.
    permission: op
    permission-message: Unknown command. Type "/help" for help.