name: FileManager
api-version: 1.14.4
version: ${project.version}
main: com.github.tanokun.filemanager.FileManager
authors: [ tanoKun ]
depend: [ProtocolLib]
description: Plugin for editing files. 

commands:
  files:
    description: open the files menu.
    permission: op
    permission-message: Unknown command. Type "/help" for help.